"""After edit 

Revision ID: 111fd4ccb0fb
Revises: 9046b6d6a906
Create Date: 2021-05-23 16:53:11.890344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111fd4ccb0fb'
down_revision = '9046b6d6a906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_product',
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('color_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('color_product')
    op.drop_table('color')
    # ### end Alembic commands ###
